# Generated by Django 3.1.3 on 2020-11-12 10:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ListaDruzyn',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa_druzyny', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Zawodnik',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Imie', models.CharField(max_length=64, null=True)),
                ('Nazwisko', models.CharField(max_length=64, null=True)),
                ('Wiek', models.PositiveSmallIntegerField()),
                ('Pozycja_na_boisku', models.PositiveSmallIntegerField(choices=[(1, 'Środkowy obrońca'), (6, 'Wahadłowy'), (5, 'Boczny pomocnik'), (3, 'Środkowy defensywny pomocnik'), (0, 'Bramkarz'), (7, 'Napastnik'), (4, 'Środkowy ofensywny pomocnik'), (2, 'Boczny obrońca')])),
                ('Fotografia', models.ImageField(blank=True, null=True, upload_to='fotografie_zawodnikow')),
                ('Druzyna', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Football_Players_Ratings.listadruzyn')),
            ],
        ),
    ]
