# Generated by Django 3.1.3 on 2020-11-06 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Zawodnik',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Druzyna', models.CharField(max_length=64, null=True)),
                ('Wiek', models.PositiveSmallIntegerField()),
                ('Pozycja_na_boisku', models.PositiveSmallIntegerField(choices=[(7, 'Napastnik'), (1, 'Środkowy obrońca'), (3, 'Środkowy defensywny pomocnik'), (4, 'Środkowy ofensywny pomocnik'), (5, 'Boczny pomocnik'), (6, 'Wahadłowy'), (2, 'Boczny obrońca'), (0, 'Bramkarz')])),
            ],
        ),
    ]
