# Generated by Django 3.1.3 on 2020-11-06 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Football_Players_Ratings', '0002_auto_20201106_1250'),
    ]

    operations = [
        migrations.AddField(
            model_name='zawodnik',
            name='Imie',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='zawodnik',
            name='Nazwisko',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='zawodnik',
            name='Pozycja_na_boisku',
            field=models.PositiveSmallIntegerField(choices=[(4, 'Środkowy ofensywny pomocnik'), (6, 'Wahadłowy'), (3, 'Środkowy defensywny pomocnik'), (2, 'Boczny obrońca'), (0, 'Bramkarz'), (7, 'Napastnik'), (5, 'Boczny pomocnik'), (1, 'Środkowy obrońca')]),
        ),
    ]
